# Site title and subtitle. This is used in _includes/header.html
title: 'Ticketmaster Mobile Studio'

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-62605735-1'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: 'http://ticketmastermobilestudio.github.io'

# Exclude non-site files
exclude: ['README.md']

# CSS
sass:
    style: compressed