# Site title and subtitle. This is used in _includes/header.html
title: 'Ticketmaster Mobile Studio'

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-62605735-1'

# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project

baseurl: ''


# Exclude non-site files
exclude: ['README.md']

# CSS
sass:
    style: compressed

# Display Posts Dated in the Future
future: true

# Fix Permalinks
permalink: "/:categories/:title"

# Redirects
gems:
  - jekyll-redirect-from
  - jekyll-paginate

# Blog posts per page and url structure
paginate: 8
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      hidden: true
  -
    scope:
      path: "_posts/blog"
      type: "posts"
    values:
      category: blog
      layout: blog-detail
      permalink: "/blog/:title"
      hidden: false
      # excerpt_separator: <!--more-->
